name: thesis2
dependencies:
- alabaster=0.7.7=py27_0
- appnope=0.1.0=py27_0
- astroid=1.4.4=py27_0
- babel=2.2.0=py27_0
- backports_abc=0.4=py27_0
- csvkit=0.9.1=py27_1
- cycler=0.9.0=py27_0
- dbf=0.96.003=py27_0
- decorator=4.0.9=py27_0
- docutils=0.12=py27_0
- enum34=1.1.2=py27_0
- et_xmlfile=1.0.1=py27_0
- freetype=2.5.5=0
- icu=56.1=0
- ipykernel=4.3.1=py27_0
- ipython=4.1.2=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- jdcal=1.2=py27_0
- jedi=0.8.1=py27_0
- jinja2=2.8=py27_0
- jpeg=8d=1
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.1.0=py27_0
- jupyter_core=4.0.6=py27_0
- lazy-object-proxy=1.2.1=py27_0
- libpng=1.6.17=0
- line_profiler=1.0=py27_0
- logilab-common=1.0.2=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- memory_profiler=0.40=py27_0
- mistune=0.7.1=py27_0
- mkl=11.3.1=0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.1.0=py27_0
- numpy=1.10.4=py27_0
- openpyxl=2.3.2=py27_0
- openssl=1.0.2g=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- patsy=0.4.0=np110py27_0
- pep8=1.7.0=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=8.1.1=py27_1
- psutil=4.1.0=py27_1
- ptyprocess=0.5=py27_0
- pyflakes=1.1.0=py27_0
- pygments=2.1.1=py27_0
- pylint=1.5.4=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_2
- pyqt5=5.5.0=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyzmq=15.2.0=py27_0
- qt=4.8.7=2
- qt5=5.5.0=0
- qtawesome=0.2.0=py_0
- qtconsole=4.1.1=py27_0
- qtpy=1.0.2=py27_0
- readline=6.2=2
- requests=2.9.1=py27_0
- rope=0.9.4=py27_1
- scikit-learn=0.17=np110py27_2
- scipy=0.17.0=np110py27_0
- seaborn=0.7.0=py27_0
- setuptools=20.6.7=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.3.5=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- spyder=3.0.0b3=py27_10
- sqlalchemy=1.0.12=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np110py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- wheel=0.29.0=py27_0
- wrapt=1.10.6=py27_0
- xlrd=0.9.4=py27_0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - caniusepython3==3.3.0
  - cython==0.24
  - distlib==0.2.2
  - et-xmlfile==1.0.1
  - futures==3.0.4
  - gpy==1.0.9
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - line-profiler==1.0
  - memory-profiler==0.40
  - objgraph==2.0.1
  - paramz==0.5.5
  - pyephem==3.7.6.0
  - python-contrib-nbextensions==alpha
  - pyyaml==3.11
  - sphinx-rtd-theme==0.1.9
  - theano==0.7.0
  - xdot==0.6

